Playable Prefabs of characters.
characters are glitchy when implemented. This error presents itself. Not
sure why.
NullReferenceException: Object reference not set to an instance of an
object
NavBehavior.OnTriggerEnter (UnityEngine.Collider coll) (at
Assets/Scripts/NavBehavior.cs:8)